### ISSUE TITLE
Section search

### ISSUE THREAD

**Issue by BossJC69** [crux-lab/sectioned-recycler-view#6]
Hi, is there a way to search for all adapter with filterable for example?
Thanks

**Comment by lizapopova** [comment]
Hi @BossJC69,
If I understood you correctly, you want to filter items in all of the sections simultaneously.
Unfortunately, the internal `RecyclerView.Adapter` implementation used by the library doesn't provide such functionality. Also because different sections might represent different data, it makes sense to perform filtering by section.

As a solution, you can implement [Filterable](https://developer.android.com/reference/android/widget/Filterable) interface by each section adapter separately. Then, when new query is available, you can traverse all sections and call `filter` on each `SectionAdapter`. Something like this:

```
for (index in 0 until sectionDataManager.sectionCount) {
    val sectionAdapter = sectionDataManager.getSectionAdapter<BaseSectionAdapter<*>>(index)
    (sectionAdapter as? Filterable)?.filter?.filter(query)
}
```
Let me know if my answer was helpful or you encounter problems with implementing that.

**Comment by BossJC69** [comment]
Hello. Thank you for your reply. I tried that but didn't work. In the adapter when I publish the results of the filter, I need to call notifyDataSetChanged() but that adapter doesn't have that method.

**Comment by lizapopova** [comment]
Hi @BossJC69,
This is a nice catch that `notifyDataSetChanged` method is absent. Fortunately, there is a pending [pull-request](https://github.com/crux-lab/sectioned-recycler-view/pull/7) that fixes this problem, I will try to review it on weekend.

For now, you can do the following (in Java):
```
@Override
protected void publishResults(CharSequence charSequence, FilterResults filterResults) {
    int oldSize = yourData.size();
    yourData = (ArrayList<YourItemType>) filterResults.values;
    int newSize = yourData.size();
    if (oldSize < newSize) {
        notifyItemRangeInserted(oldSize, newSize - oldSize);
    } else if (newSize < oldSize) {
        notifyItemRangeRemoved(newSize, oldSize - newSize);
    }
    if (Math.min(newSize, oldSize) > 0) {
        notifyItemRangeChanged(0, Math.min(newSize, oldSize));
    }
}
```
Hope this helps.

**Comment by BossJC69** [comment]
Thank you!

**Comment by lizapopova** [comment]
Now you can update to version **1.0.3** where `notifyDataSetChanged` method is available.
